// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApTFvi4anxLCwvxo_QqXGSNtIAiyA1XwE',
    appId: '1:1048604577644:web:cf2cb83e3af53291006d49',
    messagingSenderId: '1048604577644',
    projectId: 'muscle-mate-app-bce15',
    authDomain: 'muscle-mate-app-bce15.firebaseapp.com',
    storageBucket: 'muscle-mate-app-bce15.appspot.com',
    measurementId: 'G-S59QEWDY81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbud38YjWu1mNFTulw61lyQ7cHdzwHSQ',
    appId: '1:1048604577644:android:39aba683052bf0eb006d49',
    messagingSenderId: '1048604577644',
    projectId: 'muscle-mate-app-bce15',
    storageBucket: 'muscle-mate-app-bce15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWCQzP12WZ_M65TSmRjJS-GxfEnkbuSY',
    appId: '1:1048604577644:ios:e4e6ef107c7cbccc006d49',
    messagingSenderId: '1048604577644',
    projectId: 'muscle-mate-app-bce15',
    storageBucket: 'muscle-mate-app-bce15.appspot.com',
    iosBundleId: 'com.example.musclemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWCQzP12WZ_M65TSmRjJS-GxfEnkbuSY',
    appId: '1:1048604577644:ios:e4e6ef107c7cbccc006d49',
    messagingSenderId: '1048604577644',
    projectId: 'muscle-mate-app-bce15',
    storageBucket: 'muscle-mate-app-bce15.appspot.com',
    iosBundleId: 'com.example.musclemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApTFvi4anxLCwvxo_QqXGSNtIAiyA1XwE',
    appId: '1:1048604577644:web:96568d0bb812028b006d49',
    messagingSenderId: '1048604577644',
    projectId: 'muscle-mate-app-bce15',
    authDomain: 'muscle-mate-app-bce15.firebaseapp.com',
    storageBucket: 'muscle-mate-app-bce15.appspot.com',
    measurementId: 'G-HXDB1M21BS',
  );
}
